id: P004302
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24723
  title: ཀརྨ་བསྟན་འཕེལ་གྱི་སྨན་ཡིག
  author: ''
  volumes:
    713e37b7ed53412e9078b6645a5cdfb5:
      image_group_id: I1KG24725
      title: ''
      volume_number: 1
      total_pages: 297
