id: P004302
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:08:58.487156
source_metadata:
  id: bdr:W1KG24723
  title: ཀརྨ་བསྟན་འཕེལ་གྱི་སྨན་ཡིག
  author: ''
  volumes:
    713e37b7ed53412e9078b6645a5cdfb5:
      image_group_id: I1KG24725
      title: ''
      volume_number: 1
      total_pages: 297
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
