id: I4A4A03A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T01:42:19+00:00'
last_modified: '2022-06-07T21:49:26.443477+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24723
  title: ཀརྨ་བསྟན་འཕེལ་གྱི་སྨན་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8EF4:
      image_group_id: I1KG24725
      title: ''
      total_pages: 297
      order: 1
      base_file: 8EF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
